# Generated by Django 5.2 on 2025-05-21 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
        ('service', '0008_delete_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.jobs'),
        ),
    ]
