# Generated by Django 5.2 on 2025-05-21 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_userform_job'),
        ('service', '0008_delete_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='service.jobs'),
        ),
    ]
