# Generated by Django 5.2 on 2025-05-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_alter_userform_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
