# Generated by Django 5.2.4 on 2025-08-06 20:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_alter_userform_phone'),
        ('service', '0008_delete_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 6, 13, 14, 3, 55349)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userform',
            name='job',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='service.jobs'),
        ),
    ]
