# Generated by Django 5.2 on 2025-05-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_description', models.TextField()),
                ('service_title', models.CharField(max_length=100)),
                ('serviec_bar', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
