# Generated by Django 5.2 on 2025-05-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_table_delete_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table',
            new_name='Service',
        ),
    ]
