# Generated by Django 5.2 on 2025-05-15 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_rename_table_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='serviec_bar',
            new_name='service_bar',
        ),
    ]
