# Generated by Django 5.2 on 2025-05-15 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_rename_serviec_bar_service_service_bar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_bar',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_name',
        ),
    ]
