# Generated by Django 5.2 on 2025-05-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_remove_service_service_bar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('job_image', models.ImageField(default=None, max_length=250, null=True, upload_to='news/')),
            ],
        ),
    ]
