# Generated by Django 5.2 on 2025-05-21 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_jobs_job_image_jobapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
